# INT420-491 : Intro Python Programming
45-minutes study


## Variable & Indexing 

Variables do not need to be declared (ไม่ต้องมีการประกาศตัวแปร)


In [1]:
x = 5.
print(x)

str = "niwan"
print(str[1])
print(str[-2])
type(x)

5.0
i
a


float

## List
- List values are placed in between  [ ] 
- Each element separated by , 


In [2]:
color =["red", "green","blue"]
print(color[1]+color[0])
print(color[1],color[0])


greenred
green red


In [3]:
fruit = ["apple","orange","banana"]
fruit.append("mango")
fruit.insert(1,"storeberry")

a = input("Enter text >> ")
if a in fruit:
    print(a + " is a fruit.")
else:
    print(a + " is not a fruit.")

print(fruit)

apple is a fruit.
['apple', 'storeberry', 'orange', 'banana', 'mango']


In [4]:
num1 = [1,2,3]
num2 = [10,20,30]
num1+num2

[1, 2, 3, 10, 20, 30]

## Tuples
- Tuple values are placed in between ( )
- Each element separated by , 
- Tuples are unchangeable.


In [5]:
#tuples
color1 = ("red","green","blue") 

#list
color2 = ["red","green","blue"]

print(type(color1))
print(type(color2))

color2[1] = "black"  #list เปลี่ยนค่าได้ 

print(color1[1])
print(color2[1])

<class 'tuple'>
<class 'list'>
green
black


## Set

- Set values are placed in between { }
- Each element separated by , 

- non-dupplicated members

- index is unable 


In [10]:
#set
num1 = {1,5,7,7,10}

#list
num2 = [1,5,7,7,10]

#tuple
num3 = (1,5,7,7,10)

print(len(num1))
print(len(num2))
print(len(num3))

#print(num1[2]) # set ไม่สามารถ index ได้
print(num2[-2])
print(num3[2])

print(num1)



4
5
5
7
7
{1, 10, 5, 7}


## Dictionary

- Syntax:  {"key1": val1, "key2": val2 } 

- Values in a Python dictionary can be accessed by placing the key within square brackets next to the dictionary.


In [12]:
my_dictionary = {"song": "How You Like That", "artist": "BLACKPINK"}
print(my_dictionary["song"])
my_dictionary["song"] = "Don't Know What To Do"
print(my_dictionary["song"])


How You Like That
Don't Know What To Do


In [13]:
person = {"name":["nat", "non", "nan", "noi", "niw"], 
          "age":[15,23,18,19,18]}
print(person["name"][2])
print(person["age"][2])


nan
18


In [17]:
a = [{'a': "1"}, {'b': "2"}]
print(a)
print(a[0]['a'])

[{'a': '1'}, {'b': '2'}]
1


## For, If-else, While

In [ ]:
number = [1,2,5,6,8]
for x in number:
    if x%2 == 0:
        print(x)
    else:
        print(x+1)

In [ ]:
i = 1 
while i<5 :
    print("ans:",i)
    i+=1

## range() function 
The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.


In [18]:
x = ["A","B","O","AB"]
for i in range(4) :  
    print(i,x[i])

0 A
1 B
2 O
3 AB


In [19]:
for i in range(3,5) :  
    print(i)
    i = i+1

3
4


In [24]:
for i in range(2,10,3) :  
    print(i)
    i = i+1

2
5
8


## User-Defined Functions

In [ ]:
#%%writefile my_py_function.py
def myfunc():
    print("This is a function.")

def myfunc2(n=0):
    if n==0 :
        print("default parameter is ", n)
    else:
        print("n is", n)
        
def mul(x,y):
    m = x*y
    return m

myfunc()
myfunc2()
myfunc2(5)
a = mul(2,4)
print(a)

In [ ]:
myfunc()
myfunc2()
myfunc2(5)
a = mul(2,4)
print(a)

## Load User-defined Functions from file

We need to load functions from my_py_function.py

In [ ]:
import my_py_function as mf


In [ ]:
mf.myfunc()
mf.myfunc2()
mf.myfunc2(5)
a = mf.mul(2,4)
print(a)

In [ ]:
from my_py_function import mul
mul(5,8)

## Classes

In [25]:
#Create a Class
class myNN:
    x = 7
    y = 9

    def mul(self,a,b):
        return a*b
        

In [26]:
#Create Object
a = myNN()

print("x=",a.x," y=",a.y)

a.x = 10
a.y = 15
print("x=",a.x," y=",a.y)

a.mul(3,4)


x= 7  y= 9
x= 10  y= 15


12

### \_\_init\_\_( ) Function

Always executed when the class is being initiated

In [27]:
#Create a Class
class myNN:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def weight(self):
        w = self.x
        for i in range(len(w)):
            w[i] = w[i]*w[i]
        return w
        

In [28]:
p = myNN([2,3],[1, 0])

In [29]:
p.weight()


[4, 9]

In [30]:
class niwanAna:
    
    def getX(self,x):
        self.x = x

    def scaleX(self):
        minX = min(self.x)
        maxX = max(self.x)
        
        a = self.x
        for i in range(len(a)):
            a[i] = (a[i]-minX)/(maxX-minX) 
        
        return a
        
p = niwanAna()
p.getX([4,5,2,1,6])

p.scaleX()


[0.6, 0.8, 0.2, 0.0, 1.0]

## NumPy

NumPy is the fundamental package for scientific computing in Python


In [32]:
import numpy as np

In [33]:
#print(dir(np))

#List
a = [9,1,7,5,6]
b = [5,7,8,1,3]

#1D-array
x = np.array([9,1,7,5,6])
y = np.array([5,7,8,1,3])

print(a[0]-b[0]) #List cannot be processed as the vector
print(x-y)       #numpy array can be processed as the vector 
print(x.shape)

4
[ 4 -6 -1  4  3]
(5,)


In [36]:
#2D-array
data = np.array([[2,4,5,6,8],[2,7,4,1,9]])
print(data[1,4])
print(data[0])
print(data[0,:])
print(data[1,:])
print(data[:,3])
print(data.shape)

9
[2 4 5 6 8]
[2 4 5 6 8]
[2 7 4 1 9]
[6 1]
(2, 5)


In [37]:
#3D-array
data3 = np.array([[[2,4,5,6,8],[2,7,4,1,9]], [[2,4,5,6,8],[2,7,4,1,9]]])
data3.shape

(2, 2, 5)

In [38]:
x1 = np.zeros([3,3])
y1 = np.ones([3,3])
I = np.eye(5)
print(x1)
print(y1)
print(I)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
x = [2,4,5,6]
x = np.reshape(x,[2,2])
x

array([[2, 4],
       [5, 6]])

In [40]:
np.log(x)

array([[0.69314718, 1.38629436],
       [1.60943791, 1.79175947]])

In [41]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0,5,100)
y = np.sin(x)

plt.plot(x,y)


ModuleNotFoundError: No module named 'matplotlib'

## Pandas

Powerful data structures for data analysis, time series, and statistics

https://pandas.pydata.org/ 



In [42]:
import pandas as pd

### Series 

#### Declaring

In [45]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [44]:
# Check in Consol
s
s.values
s.index

RangeIndex(start=0, stop=4, step=1)

In [47]:
s = pd.Series([12,-4,7,9], index=['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

#### Selecting the Internal Elements

In [48]:
s[2]

7

In [49]:
s['b']

-4

In [50]:
s[:3]

a    12
b    -4
c     7
dtype: int64

In [51]:
s[['b','d']]

b   -4
d    9
dtype: int64

#### Assigning Values to the Elements

In [52]:
s[2]=0
s

a    12
b    -4
c     0
d     9
dtype: int64

In [53]:
s['c'] = 8
s

a    12
b    -4
c     8
d     9
dtype: int64

In [54]:
s[['a','b']] = [12,14]
s

a    12
b    14
c     8
d     9
dtype: int64

#### Filtering Values

In [55]:
s[s<10]

c    8
d    9
dtype: int64

In [56]:
s[(s>8) & (s<14)]

a    12
d     9
dtype: int64

#### Operations and Mathematical Functions

In [57]:
import numpy as np

In [59]:
s

a    12
b    14
c     8
d     9
dtype: int64

In [60]:
s/3

a    4.000000
b    4.666667
c    2.666667
d    3.000000
dtype: float64

In [61]:
np.sqrt(s)

a    3.464102
b    3.741657
c    2.828427
d    3.000000
dtype: float64

In [62]:
np.log(s)

a    2.484907
b    2.639057
c    2.079442
d    2.197225
dtype: float64

#### Useful Methods 

In [63]:
s = pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])
s

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [66]:
a = pd.Series(['white','white','blue','green','green','yellow'])
a.unique()

array(['white', 'blue', 'green', 'yellow'], dtype=object)

In [64]:
s.unique()

array([1, 0, 2, 3], dtype=int64)

In [65]:
s.value_counts()

1    2
2    2
0    1
3    1
dtype: int64

In [67]:
s.isin([2,3])

white     False
white     False
blue       True
green     False
green      True
yellow     True
dtype: bool

In [68]:
s[s.isin([2,3])]

blue      2
green     2
yellow    3
dtype: int64

In [69]:
#Nan Value
s['white'] =  np.NaN

In [71]:
s

white     NaN
white     NaN
blue      2.0
green     1.0
green     2.0
yellow    3.0
dtype: float64

In [72]:
s.isnull()

white      True
white      True
blue      False
green     False
green     False
yellow    False
dtype: bool

In [70]:
s.isna()

white      True
white      True
blue      False
green     False
green     False
yellow    False
dtype: bool

In [ ]:
s.isnull()

In [73]:
s.notnull()

white     False
white     False
blue       True
green      True
green      True
yellow     True
dtype: bool

In [74]:
s[s.notnull()]

blue      2.0
green     1.0
green     2.0
yellow    3.0
dtype: float64

In [75]:
s.mean()

2.0

### DataFrame

#### Defining a Dataframe

In [76]:
#dict object
data = {'color' : ['blue','green','yellow','red','white'],
 'object' : ['ball','pen','pencil','paper','mug'],
 'price' : [1.2,1.0,0.6,0.9,1.7]}
data

{'color': ['blue', 'green', 'yellow', 'red', 'white'],
 'object': ['ball', 'pen', 'pencil', 'paper', 'mug'],
 'price': [1.2, 1.0, 0.6, 0.9, 1.7]}

In [77]:
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [78]:
frame2 = pd.DataFrame(data, index=['one','two','three','four','five'])
frame2

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

In [79]:
frame.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
frame.values

#### Selecting Elements

##### Select columns

In [80]:
frame.columns

Index(['color', 'object', 'price'], dtype='object')

In [81]:
frame['price']

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [82]:
frame.price

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [83]:
frame[['object','price']]

object  price
0    ball    1.2
1     pen    1.0
2  pencil    0.6
3   paper    0.9
4     mug    1.7

##### Select rows

In [84]:
#frame[2] is not available
frame.loc[2]

color     yellow
object    pencil
price        0.6
Name: 2, dtype: object

In [90]:
frame[0:3]

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6

In [91]:
frame.loc[2] = ['yellow','pencil',0.7]

In [94]:
frame.loc[[1,2]]

color  object  price
1   green     pen    1.0
2  yellow  pencil    0.7

In [95]:
frame2  # df with non-number indexing

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

In [96]:
frame2.iloc[2]

color     yellow
object    pencil
price        0.6
Name: three, dtype: object

In [99]:
frame2.loc['one']

color     blue
object    ball
price      1.2
Name: one, dtype: object

In [102]:
frame.loc[1]

color     green
object      pen
price       1.0
Name: 1, dtype: object

In [100]:
frame2[0:3]

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6

##### Select columns and rows 

In [106]:
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.7
3     red   paper    0.9
4   white     mug    1.7

In [103]:
frame['object'][3]

'paper'

In [104]:
frame.loc[3]['object']

'paper'

In [105]:
frame['object'][:-1]

0      ball
1       pen
2    pencil
3     paper
Name: object, dtype: object

#### Assigning Values

In [110]:
frame3 = frame.copy()
frame3['price'][2] = 3.9
frame3

C:\Users\patip\AppData\Local\Temp\ipykernel_14708\4198770635.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame3['price'][2] = 3.9


color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    3.9
3     red   paper    0.9
4   white     mug    1.7

In [111]:
frame3.loc[2,'price'] = 1.1
frame3

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    1.1
3     red   paper    0.9
4   white     mug    1.7

In [118]:
frame3['new'] = [3.0,1.3,2.2,0.8,1.1]
frame3

color  object  price  new
0    blue    ball    1.2  3.0
1   green     pen    1.0  1.3
2  yellow  pencil    1.1  2.2
3     red   paper    0.9  0.8
4   white     mug    1.7  1.1

#### Filtering

In [119]:
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.7
3     red   paper    0.9
4   white     mug    1.7

In [113]:
frame[frame['price'] > 2]

Empty DataFrame
Columns: [color, object, price]
Index: []

In [120]:
frame[ frame['object'].isin(['ball','pen'])]

color object  price
0   blue   ball    1.2
1  green    pen    1.0

In [121]:
frame[(frame['object'].isin(['ball','pen'])) & (frame['price'] > 2)]

Empty DataFrame
Columns: [color, object, price]
Index: []

#### Deleting a Column

In [122]:
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.7
3     red   paper    0.9
4   white     mug    1.7

In [123]:
frame.drop(columns= ['new'])

KeyError: "['new'] not found in axis"

In [124]:
frame3

color  object  price  new
0    blue    ball    1.2  3.0
1   green     pen    1.0  1.3
2  yellow  pencil    1.1  2.2
3     red   paper    0.9  0.8
4   white     mug    1.7  1.1

In [125]:
del frame3['new']

In [126]:
frame3

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    1.1
3     red   paper    0.9
4   white     mug    1.7

In [127]:
frame4 = frame3.copy()
frame4

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    1.1
3     red   paper    0.9
4   white     mug    1.7

In [130]:
frame4.drop(columns=['object','price'])

color
0    blue
1   green
2  yellow
3     red
4   white